import Footer from "@/components/footer/page";
import "./globals.css";
import { Montserrat_Alternates } from "next/font/google";
import { NavBar } from "@/components/nav/nav";
import { getFooterPage } from "@/lib/actions/footer-page";

const montserrat = Montserrat_Alternates({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default async function RootLayout({ children }) {
  const { footer } = await getFooterPage();
  
  return (
    <html lang="en">
      <body className={montserrat.className}>
          <NavBar/>
          {children}
          <Footer footer={footer} />
      </body>
    </html>
  );
}
