import Footer from "@/components/footer/page";
import "./globals.css";
import { NavBar } from "@/components/nav/nav";
import { Montserrat_Alternates } from "next/font/google";

const montserrat = Montserrat_Alternates({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={montserrat.className}
      >
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
